[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["sources.json"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"