
[build]
  publish = "public"
  functions = "netlify/functions"
[functions]
  node_bundler = "esbuild"
  included_files = ["sources.json"]
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=60, stale-while-revalidate=300"
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
